package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"time"
)

type AutoGenerated struct {
	ErrCode int    `json:"ErrCode"`
	ErrMsg  string `json:"ErrMsg"`
	Data    struct {
		ServerID          int    `json:"ServerID"`
		Sentence          string `json:"Sentence"`
		QueryID           string `json:"QueryId"`
		ResultFromNlpseID bool   `json:"ResultFromNlpseID"`
		MapKeywords       struct {
			AB int `json:"AB股总市值(最新)"`
		} `json:"MapKeywords"`
		Conditions []struct {
			ARG1     string `json:"ARG1"`
			CFN      string `json:"CFN"`
			HASH     string `json:"HASH"`
			KEY      string `json:"KEY"`
			KEYDESC  string `json:"KEY_DESC"`
			KEYINPUT string `json:"KEY_INPUT"`
			KEYSHOW  string `json:"KEY_SHOW"`
			KEYTYPE  string `json:"KEY_TYPE"`
			MATCH    int    `json:"MATCH"`
			R        string `json:"R"`
			T        string `json:"T"`
			TEXT     string `json:"TEXT"`
		} `json:"Conditions"`
		ErrCode        int         `json:"ErrCode"`
		ErrMsg         string      `json:"ErrMsg"`
		TotalCount     int         `json:"TotalCount"`
		Offset         int         `json:"Offset"`
		Limit          int         `json:"Limit"`
		RowsCount      int         `json:"RowsCount"`
		Pos            string      `json:"Pos"`
		Cols           []string    `json:"Cols"`
		ColsRightAlign []string    `json:"ColsRightAlign"`
		ColMemos       interface{} `json:"ColMemos"`
		//Rows           []struct {
		//	POS            string `json:"POS"`
		//	Chg            string `json:"chg"`
		//	Market         string `json:"market"`
		//	NowPrice       string `json:"now_price"`
		//	SecCode        string `json:"sec_code"`
		//	SecName        string `json:"sec_name"`
		//	NAMING_FAILED1 string `json:"基本面"`
		//	NAMING_FAILED2 string `json:"总市值(元)"`
		//	NAMING_FAILED3 string `json:"成交额(元)"`
		//	NAMING_FAILED4 string `json:"技术面"`
		//	NAMING_FAILED5 string `json:"换手率(%)"`
		//	NAMING_FAILED6 string `json:"机构面"`
		//	NAMING_FAILED7 string `json:"综合评分"`
		//} `json:"Rows"`
		Rows    []map[string]string `json:"Rows"`
		Advices interface{}         `json:"Advices"`
		NlpseID string              `json:"NlpseID"`
		Other   string              `json:"Other"`
		Time1   time.Time           `json:"Time1"`
		Time2   time.Time           `json:"Time2"`
		Hots    []string            `json:"Hots"`
		Filters []struct {
			Label   string `json:"label"`
			Options []struct {
				S   string `json:"s"`
				Key string `json:"key"`
			} `json:"options"`
			Unit   string `json:"unit"`
			Custom int    `json:"custom"`
			Only   int    `json:"only"`
		} `json:"Filters"`
		HqKey     string      `json:"HqKey"`
		PlateInfo interface{} `json:"PlateInfo"`
		HqZsts    interface{} `json:"HqZsts"`
		HqFxts    interface{} `json:"HqFxts"`
		OtherInfo interface{} `json:"OtherInfo"`
	} `json:"Data"`
}

func main() {
	//userEmail := "username@qq.com"
	//
	//before, after, found := strings.Cut(userEmail, "@")
	//if found {
	//	log.Printf("userName: %s, email: %s", before, after)
	//}
	//return
	//fmt.Println(stringer.Reverse("脑子进煎鱼了！"))

	query := "pe小于5的公司"
	uri := "http://xg.cmschina.com/user/v1/parse"

	qParams := url.Values{}
	qParams.Set("s", query)
	qParams.Set("extra", "2")
	qParams.Set("nlpseid", "")
	qParams.Set("limit", "10")
	qParams.Set("offset", "0")
	qParams.Set("sort", "")
	qParams.Set("order", "")
	qParams.Set("tdxid", "tdxidtest")
	qParams.Set("discache", "true")

	u, err := url.ParseRequestURI(uri)
	if err != nil {
		log.Fatal(err)
	}
	u.RawQuery = qParams.Encode()

	client := &http.Client{}
	req, _ := http.NewRequest(http.MethodGet, u.String(), nil)
	req.Header.Add("User-Agent", "cmschina")

	resp, _ := client.Do(req)
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	fmt.Println("响应状态码:", resp.StatusCode)
	//fmt.Println("响应内容:", string(body))

	var res AutoGenerated
	err = json.Unmarshal(body, &res)
	if err != nil {
		panic(err)
	}

	fmt.Println("Sentence: ", res.Data.Sentence)

	for _, colName := range res.Data.Cols {
		fmt.Print(colName + " ")
	}
	fmt.Println()

	for _, rMap := range res.Data.Rows {
		fmt.Println("=======================")
		for k, v := range rMap {
			fmt.Println(k, v)
		}
	}

}

var str = `
	{
	   "ErrCode": 0,
	   "ErrMsg": "OK",
	   "Data": {
	       "ServerID": 3,
	       "Sentence": "市值大于100亿",
	       "QueryId": "27927e1ba3eb3009685bb8ad4d8f6739",
	       "ResultFromNlpseID": false,
	       "MapKeywords": {
	           "AB股总市值(最新)": 1
	       },
	       "Conditions": [
	           {
	               "ARG1": "10000000000.00",
	               "CFN": "GT",
	               "HASH": "40091aea8649e0005f5c08a693ae569b",
	               "KEY": "AB股总市值(最新)",
	               "KEY_DESC": "AB股总市值=A股总市值+B股总市值",
	               "KEY_INPUT": "市值",
	               "KEY_SHOW": "AB股总市值(最新)",
	               "KEY_TYPE": "财务面",
	               "MATCH": 1505,
	               "R": "OP",
	               "T": "40091aea8649e0005f5c08a693ae569b",
	               "TEXT": "AB股总市值(最新) > 100.00亿元"
	           }
	       ],
	       "ErrCode": 0,
	       "ErrMsg": "",
	       "TotalCount": 1505,
	       "Offset": 0,
	       "Limit": 10,
	       "RowsCount": 10,
	       "Pos": "10",
	       "Cols": [
	           "POS",
	           "market",
	           "sec_code",
	           "sec_name",
	           "now_price",
	           "chg",
	           "换手率(%)",
	           "成交额(元)",
	           "总市值(元)"
	       ],
	       "ColsRightAlign": [
	           "market",
	           "成交额(元)",
	           "总市值(元)"
	       ],
	       "ColMemos": null,
	       "Rows": [
	           {
	               "POS": "1",
	               "chg": "0.87",
	               "market": "1",
	               "now_price": "6.93",
	               "sec_code": "601398",
	               "sec_name": "工商银行",
	               "基本面": "2",
	               "总市值(元)": "2.47万亿",
	               "成交额(元)": "9.75亿",
	               "技术面": "2",
	               "换手率(%)": "0.05",
	               "机构面": "3",
	               "综合评分": "3"
	           },
	           {
	               "POS": "2",
	               "chg": "0.67",
	               "market": "1",
	               "now_price": "111.14",
	               "sec_code": "600941",
	               "sec_name": "中国移动",
	               "基本面": "3",
	               "总市值(元)": "2.40万亿",
	               "成交额(元)": "3.95亿",
	               "技术面": "2",
	               "换手率(%)": "0.39",
	               "机构面": "4",
	               "综合评分": "3"
	           },
	           {
	               "POS": "3",
	               "chg": "0.34",
	               "market": "1",
	               "now_price": "8.96",
	               "sec_code": "601939",
	               "sec_name": "建设银行",
	               "基本面": "2",
	               "总市值(元)": "2.24万亿",
	               "成交额(元)": "3.00亿",
	               "技术面": "2",
	               "换手率(%)": "0.35",
	               "机构面": "4",
	               "综合评分": "3"
	           },
	           {
	               "POS": "4",
	               "chg": "-0.07",
	               "market": "1",
	               "now_price": "1550.84",
	               "sec_code": "600519",
	               "sec_name": "贵州茅台",
	               "基本面": "3",
	               "总市值(元)": "1.95万亿",
	               "成交额(元)": "9.91亿",
	               "技术面": "4",
	               "换手率(%)": "0.05",
	               "机构面": "4",
	               "综合评分": "4"
	           },
	           {
	               "POS": "5",
	               "chg": "1.54",
	               "market": "1",
	               "now_price": "5.26",
	               "sec_code": "601288",
	               "sec_name": "农业银行",
	               "基本面": "2",
	               "总市值(元)": "1.84万亿",
	               "成交额(元)": "12.05亿",
	               "技术面": "2",
	               "换手率(%)": "0.07",
	               "机构面": "4",
	               "综合评分": "3"
	           },
	           {
	               "POS": "6",
	               "chg": "1.09",
	               "market": "1",
	               "now_price": "5.54",
	               "sec_code": "601988",
	               "sec_name": "中国银行",
	               "基本面": "2",
	               "总市值(元)": "1.63万亿",
	               "成交额(元)": "4.24亿",
	               "技术面": "2",
	               "换手率(%)": "0.04",
	               "机构面": "4",
	               "综合评分": "3"
	           },
	           {
	               "POS": "7",
	               "chg": "-0.13",
	               "market": "1",
	               "now_price": "7.68",
	               "sec_code": "601857",
	               "sec_name": "中国石油",
	               "基本面": "3",
	               "总市值(元)": "1.41万亿",
	               "成交额(元)": "3.81亿",
	               "技术面": "1",
	               "换手率(%)": "0.03",
	               "机构面": "4",
	               "综合评分": "4"
	           },
	           {
	               "POS": "8",
	               "chg": "-0.04",
	               "market": "1",
	               "now_price": "24.69",
	               "sec_code": "600938",
	               "sec_name": "中国海油",
	               "基本面": "3",
	               "总市值(元)": "1.17万亿",
	               "成交额(元)": "2.00亿",
	               "技术面": "1",
	               "换手率(%)": "0.28",
	               "机构面": "4",
	               "综合评分": "3"
	           },
	           {
	               "POS": "9",
	               "chg": "-0.40",
	               "market": "0",
	               "now_price": "357.58",
	               "sec_code": "002594",
	               "sec_name": "比亚迪",
	               "基本面": "5",
	               "总市值(元)": "1.09万亿",
	               "成交额(元)": "19.91亿",
	               "技术面": "2",
	               "换手率(%)": "0.47",
	               "机构面": "5",
	               "综合评分": "4"
	           },
	           {
	               "POS": "10",
	               "chg": "0.51",
	               "market": "1",
	               "now_price": "41.69",
	               "sec_code": "600036",
	               "sec_name": "招商银行",
	               "基本面": "2",
	               "总市值(元)": "1.05万亿",
	               "成交额(元)": "5.11亿",
	               "技术面": "2",
	               "换手率(%)": "0.06",
	               "机构面": "2",
	               "综合评分": "2"
	           }
	       ],
	       "Advices": null,
	       "NlpseID": "",
	       "Other": "",
	       "Time1": "0001-01-01T00:00:00Z",
	       "Time2": "2025-04-15T10:22:39.198269002+08:00",
	       "Hots": [
	           "市值小于30亿",
	           "筹码集中70%  均线多头向上 总市值小于50亿;归属于母公司所有者的净利润大于10000000",
	           "连续3年每股收益同比增长率大于25%, AB股总市值(最新) < 130.00亿元;市盈(动) < 25.00倍;销售毛利率 > 30.00%;近三年归属于母公司所有者的净利润 > 0.00元,净利润同比增长大于30%",
	           "市值300亿以上的",
	           "市值小于20亿",
	           "A股市值小于20亿 市盈率小于20",
	           "银行市值排行",
	           "利润>3亿,总市值<50亿",
	           "低位筹码密集 均线多头向上 总市值小于50亿;归属于母公司所有者的净利润大于0小于100000000",
	           "MSCI成份 市值"
	       ],
	       "Filters": [
	           {
	               "label": "涨跌幅",
	               "options": [
	                   {
	                       "s": "涨跌幅小于-5%",
	                       "key": "涨跌幅"
	                   },
	                   {
	                       "s": "涨跌幅大于-5%小于0%",
	                       "key": "涨跌幅"
	                   },
	                   {
	                       "s": "涨跌幅大于0%小于5%",
	                       "key": "涨跌幅"
	                   },
	                   {
	                       "s": "涨跌幅大于5%",
	                       "key": "涨跌幅"
	                   }
	               ],
	               "unit": "%",
	               "custom": 1,
	               "only": 1
	           },
	           {
	               "label": "换手率",
	               "options": [
	                   {
	                       "s": "换手率小于1%",
	                       "key": "换手率"
	                   },
	                   {
	                       "s": "换手率大于1%小于3%",
	                       "key": "换手率"
	                   },
	                   {
	                       "s": "换手率大于3%小于5%",
	                       "key": "换手率"
	                   },
	                   {
	                       "s": "换手率大于5%",
	                       "key": "换手率"
	                   }
	               ],
	               "unit": "%",
	               "custom": 1,
	               "only": 1
	           },
	           {
	               "label": "动态市盈率",
	               "options": [
	                   {
	                       "s": "市盈率小于0",
	                       "key": "市盈(动)"
	                   },
	                   {
	                       "s": "市盈率大于0小于25",
	                       "key": "市盈(动)"
	                   },
	                   {
	                       "s": "市盈率大于25小于50",
	                       "key": "市盈(动)"
	                   },
	                   {
	                       "s": "市盈率大于50",
	                       "key": "市盈(动)"
	                   }
	               ],
	               "unit": "倍",
	               "custom": 1,
	               "only": 1
	           },
	           {
	               "label": "净利润",
	               "options": [
	                   {
	                       "s": "净利润小于0亿元",
	                       "key": "归属于母公司所有者的净利润"
	                   },
	                   {
	                       "s": "净利润大于0亿元小于1亿元",
	                       "key": "归属于母公司所有者的净利润"
	                   },
	                   {
	                       "s": "净利润大于1亿元小于10亿元",
	                       "key": "归属于母公司所有者的净利润"
	                   },
	                   {
	                       "s": "净利润大于10亿元",
	                       "key": "归属于母公司所有者的净利润"
	                   }
	               ],
	               "unit": "亿元",
	               "custom": 1,
	               "only": 1
	           },
	           {
	               "label": "指标",
	               "options": [
	                   {
	                       "s": "KDJ金叉",
	                       "key": "KDJ金叉"
	                   },
	                   {
	                       "s": "KDJ底背离",
	                       "key": "KDJ底背离"
	                   },
	                   {
	                       "s": "MACD金叉",
	                       "key": "MACD金叉"
	                   },
	                   {
	                       "s": "MACD低位金叉",
	                       "key": "MACD低位金叉"
	                   },
	                   {
	                       "s": "短线多头",
	                       "key": "短线多头"
	                   },
	                   {
	                       "s": "上升通道",
	                       "key": "上升通道"
	                   },
	                   {
	                       "s": "价量齐升",
	                       "key": "价量齐升"
	                   },
	                   {
	                       "s": "中线超跌",
	                       "key": "中线超跌"
	                   },
	                   {
	                       "s": "跳空缺口",
	                       "key": "跳空缺口"
	                   }
	               ],
	               "unit": "",
	               "custom": 0,
	               "only": 0
	           }
	       ],
	       "HqKey": "",
	       "PlateInfo": null,
	       "HqZsts": null,
	       "HqFxts": null,
	       "OtherInfo": null
	   }
	}
	`
