### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

###


# curl --location --request POST 'http://localhost:8080/playwright/version'
POST http://localhost:8080/playwright/version

###



# curl --location 'http://localhost:11434/api/chat'
#--header 'Content-Type: application/json'
#--data '{
#  "model": "qwen3:0.6b",
#  "messages": [
#    {
#      "role": "user",
#      "content": "写个对联"
#    }
#  ],
#  "stream": false,
#  "options": {
#    "temperature": 0.7,
#    "max_tokens": 100
#  }
#}'
POST http://localhost:11434/api/chat
Content-Type: application/json

{
  "model": "qwen3:0.6b",
  "messages": [
    {
      "role": "user",
      "content": "写个对联"
    }
  ],
  "stream": false,
  "options": {
    "temperature": 0.7,
    "max_tokens": 1000
  }
}

###

